import { useState } from "react";
import { Eye, EyeOff, Loader2 } from "lucide-react";
import { Button } from "./ui/button";
import { Input } from "./ui/input";
import { Label } from "./ui/label";
import { api } from "@/lib/api";
import { useAuth } from "@/lib/auth-context";

interface LoginProps {
  onLogin: () => void;
}

interface LoginResponse {
  token: string;
  user: { id: string; username: string; role: string };
}

export function Login({ onLogin }: LoginProps) {
  const { login } = useAuth();
  const [username, setUsername]       = useState("");
  const [password, setPassword]       = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError]             = useState("");
  const [loading, setLoading]         = useState(false);

  async function handleSignIn() {
    if (!username.trim() || !password.trim()) {
      setError("Please enter your username and password.");
      return;
    }
    setError("");
    setLoading(true);
    try {
      const res = await api.post<LoginResponse>("/api/auth/login", {
        username: username.trim(),
        password,
      });
      login(res.token, res.user);
      onLogin();
    } catch (err) {
      setError((err as Error).message || "Login failed. Check your credentials.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      className="min-h-screen w-full flex flex-col items-center justify-center"
      style={{ backgroundColor: "#f8fafc" }}
    >
      <div className="w-full max-w-sm shadow-lg rounded-xl overflow-hidden">
        {/* Header */}
        <div className="px-8 py-8 text-center" style={{ backgroundColor: "#1e293b" }}>
          <div className="flex justify-center mb-4">
            <img
              src="/logo.png"
              alt="Logo"
              className="h-14 w-14 rounded-xl object-cover"
              onError={(e) => { (e.currentTarget as HTMLImageElement).style.display = "none"; }}
            />
          </div>
          <p className="text-white text-xl font-semibold">Abaad ERP</p>
          <p className="text-sm mt-1" style={{ color: "#94a3b8" }}>
            3D Printing Management System
          </p>
        </div>

        {/* Form */}
        <div className="bg-white px-8 py-8 space-y-5">
          <div className="space-y-1.5">
            <Label htmlFor="username" style={{ color: "#0f172a" }}>Username</Label>
            <Input
              id="username"
              placeholder="Enter username"
              value={username}
              autoComplete="username"
              disabled={loading}
              onChange={(e) => setUsername(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && handleSignIn()}
            />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="password" style={{ color: "#0f172a" }}>Password</Label>
            <div className="relative">
              <Input
                id="password"
                type={showPassword ? "text" : "password"}
                placeholder="Enter password"
                value={password}
                autoComplete="current-password"
                className="pr-10"
                disabled={loading}
                onChange={(e) => setPassword(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleSignIn()}
              />
              <button
                type="button"
                onClick={() => setShowPassword((s) => !s)}
                className="absolute inset-y-0 end-0 flex items-center px-3 text-[#94a3b8] hover:text-[#64748b] transition-colors"
                tabIndex={-1}
              >
                {showPassword ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
          </div>

          {error && (
            <p className="text-sm rounded-md px-3 py-2 bg-red-50 text-red-600 border border-red-200">
              {error}
            </p>
          )}

          <Button
            className="w-full text-white font-medium hover:opacity-90"
            style={{ backgroundColor: "#1e3a8a" }}
            onClick={handleSignIn}
            disabled={loading}
          >
            {loading ? (
              <>
                <Loader2 size={16} className="mr-2 animate-spin" />
                Signing in…
              </>
            ) : (
              "Sign In"
            )}
          </Button>
        </div>
      </div>

      <p className="mt-6 text-xs" style={{ color: "#94a3b8" }}>
        Generated by Abaad ERP
      </p>
    </div>
  );
}
